name: Generate PDFs from C Files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to trigger the action manually from the Actions tab

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          pip install Pygments

      - name: Make script executable
        run: chmod +x .github/scripts/generate_pdfs.sh

      - name: Run conversion script
        env:
          TARGET_FOLDER: "workspace" 
        run: .github/scripts/generate_pdfs.sh

      - name: Upload PDFs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: highlighted-c-pdfs
          path: output_pdfs/
          retention-days: 7